INSERT INTO Realms (id, name, slug, RegionID) VALUES 
(1, 'Aegwynn', 'aegwynn', 1), 
(2, 'Aerie Peak', 'aerie-peak', 1), 
(3, 'Agamaggan', 'agamaggan', 1), 
(4, 'Aggramar', 'aggramar', 1), 
(5, 'Akama', 'akama', 1), 
(6, 'Alexstrasza', 'alexstrasza', 1), 
(7, 'Alleria', 'alleria', 1), 
(8, 'Altar of Storms', 'altar-of-storms', 1), 
(9, 'Alterac Mountains', 'alterac-mountains', 1), 
(10, 'Aman''Thul', 'amanthul', 1), 
(11, 'Andorhal', 'andorhal', 1), 
(12, 'Anetheron', 'anetheron', 1), 
(13, 'Antonidas', 'antonidas', 1), 
(14, 'Anub''arak', 'anubarak', 1), 
(15, 'Anvilmar', 'anvilmar', 1), 
(16, 'Arathor', 'arathor', 1), 
(17, 'Archimonde', 'archimonde', 1), 
(18, 'Area 52', 'area-52', 1), 
(19, 'Argent Dawn', 'argent-dawn', 1), 
(20, 'Arthas', 'arthas', 1), 
(21, 'Arygos', 'arygos', 1), 
(22, 'Auchindoun', 'auchindoun', 1), 
(23, 'Azgalor', 'azgalor', 1), 
(24, 'Azjol-Nerub', 'azjolnerub', 1), 
(25, 'Azralon', 'azralon', 1), 
(26, 'Azshara', 'azshara', 1), 
(27, 'Azuremyst', 'azuremyst', 1), 
(28, 'Baelgun', 'baelgun', 1), 
(29, 'Balnazzar', 'balnazzar', 1), 
(30, 'Barthilas', 'barthilas', 1), 
(31, 'Black Dragonflight', 'black-dragonflight', 1), 
(32, 'Blackhand', 'blackhand', 1), 
(33, 'Blackrock', 'blackrock', 1), 
(34, 'Blackwater Raiders', 'blackwater-raiders', 1), 
(35, 'Blackwing Lair', 'blackwing-lair', 1), 
(36, 'Blade''s Edge', 'blades-edge', 1), 
(37, 'Bladefist', 'bladefist', 1), 
(38, 'Bleeding Hollow', 'bleeding-hollow', 1), 
(39, 'Blood Furnace', 'blood-furnace', 1), 
(40, 'Bloodhoof', 'bloodhoof', 1), 
(41, 'Bloodscalp', 'bloodscalp', 1), 
(42, 'Bonechewer', 'bonechewer', 1), 
(43, 'Borean Tundra', 'borean-tundra', 1), 
(44, 'Boulderfist', 'boulderfist', 1), 
(45, 'Bronzebeard', 'bronzebeard', 1), 
(46, 'Burning Blade', 'burning-blade', 1), 
(47, 'Burning Legion', 'burning-legion', 1), 
(48, 'Caelestrasz', 'caelestrasz', 1), 
(49, 'Cairne', 'cairne', 1), 
(50, 'Cenarion Circle', 'cenarion-circle', 1), 
(51, 'Cenarius', 'cenarius', 1), 
(52, 'Cho''gall', 'chogall', 1), 
(53, 'Chromaggus', 'chromaggus', 1), 
(54, 'Coilfang', 'coilfang', 1), 
(55, 'Crushridge', 'crushridge', 1), 
(56, 'Daggerspine', 'daggerspine', 1), 
(57, 'Dalaran', 'dalaran', 1), 
(58, 'Dalvengyr', 'dalvengyr', 1), 
(59, 'Dark Iron', 'dark-iron', 1), 
(60, 'Darkspear', 'darkspear', 1), 
(61, 'Darrowmere', 'darrowmere', 1), 
(62, 'Dath''Remar', 'dathremar', 1), 
(63, 'Dawnbringer', 'dawnbringer', 1), 
(64, 'Deathwing', 'deathwing', 1), 
(65, 'Demon Soul', 'demon-soul', 1), 
(66, 'Dentarg', 'dentarg', 1), 
(67, 'Destromath', 'destromath', 1), 
(68, 'Dethecus', 'dethecus', 1), 
(69, 'Detheroc', 'detheroc', 1), 
(70, 'Doomhammer', 'doomhammer', 1), 
(71, 'Draenor', 'draenor', 1), 
(72, 'Dragonblight', 'dragonblight', 1), 
(73, 'Dragonmaw', 'dragonmaw', 1), 
(74, 'Drak''Tharon', 'draktharon', 1), 
(75, 'Drak''thul', 'drakthul', 1), 
(76, 'Draka', 'draka', 1), 
(77, 'Drakkari', 'drakkari', 1), 
(78, 'Dreadmaul', 'dreadmaul', 1), 
(79, 'Drenden', 'drenden', 1), 
(80, 'Dunemaul', 'dunemaul', 1), 
(81, 'Durotan', 'durotan', 1), 
(82, 'Duskwood', 'duskwood', 1), 
(83, 'Earthen Ring', 'earthen-ring', 1), 
(84, 'Echo Isles', 'echo-isles', 1), 
(85, 'Eitrigg', 'eitrigg', 1), 
(86, 'Eldre''Thalas', 'eldrethalas', 1), 
(87, 'Elune', 'elune', 1), 
(88, 'Emerald Dream', 'emerald-dream', 1), 
(89, 'Eonar', 'eonar', 1), 
(90, 'Eredar', 'eredar', 1), 
(91, 'Executus', 'executus', 1), 
(92, 'Exodar', 'exodar', 1), 
(93, 'Farstriders', 'farstriders', 1), 
(94, 'Feathermoon', 'feathermoon', 1), 
(95, 'Fenris', 'fenris', 1), 
(96, 'Firetree', 'firetree', 1), 
(97, 'Fizzcrank', 'fizzcrank', 1), 
(98, 'Frostmane', 'frostmane', 1), 
(99, 'Frostmourne', 'frostmourne', 1), 
(100, 'Frostwolf', 'frostwolf', 1), 
(101, 'Galakrond', 'galakrond', 1), 
(102, 'Gallywix', 'gallywix', 1), 
(103, 'Garithos', 'garithos', 1), 
(104, 'Garona', 'garona', 1), 
(105, 'Garrosh', 'garrosh', 1), 
(106, 'Ghostlands', 'ghostlands', 1), 
(107, 'Gilneas', 'gilneas', 1), 
(108, 'Gnomeregan', 'gnomeregan', 1), 
(109, 'Goldrinn', 'goldrinn', 1), 
(110, 'Gorefiend', 'gorefiend', 1), 
(111, 'Gorgonnash', 'gorgonnash', 1), 
(112, 'Greymane', 'greymane', 1), 
(113, 'Grizzly Hills', 'grizzly-hills', 1), 
(114, 'Gul''dan', 'guldan', 1), 
(115, 'Gundrak', 'gundrak', 1), 
(116, 'Gurubashi', 'gurubashi', 1), 
(117, 'Hakkar', 'hakkar', 1), 
(118, 'Haomarush', 'haomarush', 1), 
(119, 'Hellscream', 'hellscream', 1), 
(120, 'Hydraxis', 'hydraxis', 1), 
(121, 'Hyjal', 'hyjal', 1), 
(122, 'Icecrown', 'icecrown', 1), 
(123, 'Illidan', 'illidan', 1), 
(124, 'Jaedenar', 'jaedenar', 1), 
(125, 'Jubei''Thos', 'jubeithos', 1), 
(126, 'Kael''thas', 'kaelthas', 1), 
(127, 'Kalecgos', 'kalecgos', 1), 
(128, 'Kargath', 'kargath', 1), 
(129, 'Kel''Thuzad', 'kelthuzad', 1), 
(130, 'Khadgar', 'khadgar', 1), 
(131, 'Khaz Modan', 'khaz-modan', 1), 
(132, 'Khaz''goroth', 'khazgoroth', 1), 
(133, 'Kil''jaeden', 'kiljaeden', 1), 
(134, 'Kilrogg', 'kilrogg', 1), 
(135, 'Kirin Tor', 'kirin-tor', 1), 
(136, 'Korgath', 'korgath', 1), 
(137, 'Korialstrasz', 'korialstrasz', 1), 
(138, 'Kul Tiras', 'kul-tiras', 1), 
(139, 'Laughing Skull', 'laughing-skull', 1), 
(140, 'Lethon', 'lethon', 1), 
(141, 'Lightbringer', 'lightbringer', 1), 
(142, 'Lightning''s Blade', 'lightnings-blade', 1), 
(143, 'Lightninghoof', 'lightninghoof', 1), 
(144, 'Llane', 'llane', 1), 
(145, 'Lothar', 'lothar', 1), 
(146, 'Madoran', 'madoran', 1), 
(147, 'Maelstrom', 'maelstrom', 1), 
(148, 'Magtheridon', 'magtheridon', 1), 
(149, 'Maiev', 'maiev', 1), 
(150, 'Mal''Ganis', 'malganis', 1), 
(151, 'Malfurion', 'malfurion', 1), 
(152, 'Malorne', 'malorne', 1), 
(153, 'Malygos', 'malygos', 1), 
(154, 'Mannoroth', 'mannoroth', 1), 
(155, 'Medivh', 'medivh', 1), 
(156, 'Misha', 'misha', 1), 
(157, 'Mok''Nathal', 'moknathal', 1), 
(158, 'Moon Guard', 'moon-guard', 1), 
(159, 'Moonrunner', 'moonrunner', 1), 
(160, 'Mug''thol', 'mugthol', 1), 
(161, 'Muradin', 'muradin', 1), 
(162, 'Nagrand', 'nagrand', 1), 
(163, 'Nathrezim', 'nathrezim', 1), 
(164, 'Nazgrel', 'nazgrel', 1), 
(165, 'Nazjatar', 'nazjatar', 1), 
(166, 'Nemesis', 'nemesis', 1), 
(167, 'Ner''zhul', 'nerzhul', 1), 
(168, 'Nesingwary', 'nesingwary', 1), 
(169, 'Nordrassil', 'nordrassil', 1), 
(170, 'Norgannon', 'norgannon', 1), 
(171, 'Onyxia', 'onyxia', 1), 
(172, 'Perenolde', 'perenolde', 1), 
(173, 'Proudmoore', 'proudmoore', 1), 
(174, 'Quel''Thalas', 'quelthalas', 1), 
(175, 'Quel''dorei', 'queldorei', 1), 
(176, 'Ragnaros', 'ragnaros', 1), 
(177, 'Ravencrest', 'ravencrest', 1), 
(178, 'Ravenholdt', 'ravenholdt', 1), 
(179, 'Rexxar', 'rexxar', 1), 
(180, 'Rivendare', 'rivendare', 1), 
(181, 'Runetotem', 'runetotem', 1), 
(182, 'Sargeras', 'sargeras', 1), 
(183, 'Saurfang', 'saurfang', 1), 
(184, 'Scarlet Crusade', 'scarlet-crusade', 1), 
(185, 'Scilla', 'scilla', 1), 
(186, 'Sen''jin', 'senjin', 1), 
(187, 'Sentinels', 'sentinels', 1), 
(188, 'Shadow Council', 'shadow-council', 1), 
(189, 'Shadowmoon', 'shadowmoon', 1), 
(190, 'Shadowsong', 'shadowsong', 1), 
(191, 'Shandris', 'shandris', 1), 
(192, 'Shattered Halls', 'shattered-halls', 1), 
(193, 'Shattered Hand', 'shattered-hand', 1), 
(194, 'Shu''halo', 'shuhalo', 1), 
(195, 'Silver Hand', 'silver-hand', 1), 
(196, 'Silvermoon', 'silvermoon', 1), 
(197, 'Sisters of Elune', 'sisters-of-elune', 1), 
(198, 'Skullcrusher', 'skullcrusher', 1), 
(199, 'Skywall', 'skywall', 1), 
(200, 'Smolderthorn', 'smolderthorn', 1), 
(201, 'Spinebreaker', 'spinebreaker', 1), 
(202, 'Spirestone', 'spirestone', 1), 
(203, 'Staghelm', 'staghelm', 1), 
(204, 'Steamwheedle Cartel', 'steamwheedle-cartel', 1), 
(205, 'Stonemaul', 'stonemaul', 1), 
(206, 'Stormrage', 'stormrage', 1), 
(207, 'Stormreaver', 'stormreaver', 1), 
(208, 'Stormscale', 'stormscale', 1), 
(209, 'Suramar', 'suramar', 1), 
(210, 'Tanaris', 'tanaris', 1), 
(211, 'Terenas', 'terenas', 1), 
(212, 'Terokkar', 'terokkar', 1), 
(213, 'Thaurissan', 'thaurissan', 1), 
(214, 'The Forgotten Coast', 'the-forgotten-coast', 1), 
(215, 'The Scryers', 'the-scryers', 1), 
(216, 'The Underbog', 'the-underbog', 1), 
(217, 'The Venture Co', 'the-venture-co', 1), 
(218, 'Thorium Brotherhood', 'thorium-brotherhood', 1), 
(219, 'Thrall', 'thrall', 1), 
(220, 'Thunderhorn', 'thunderhorn', 1), 
(221, 'Thunderlord', 'thunderlord', 1), 
(222, 'Tichondrius', 'tichondrius', 1), 
(223, 'Tol Barad', 'tol-barad', 1), 
(224, 'Tortheldrin', 'tortheldrin', 1), 
(225, 'Trollbane', 'trollbane', 1), 
(226, 'Turalyon', 'turalyon', 1), 
(227, 'Twisting Nether', 'twisting-nether', 1), 
(228, 'Uldaman', 'uldaman', 1), 
(229, 'Uldum', 'uldum', 1), 
(230, 'Undermine', 'undermine', 1), 
(231, 'Ursin', 'ursin', 1), 
(232, 'Uther', 'uther', 1), 
(233, 'Vashj', 'vashj', 1), 
(234, 'Vek''nilash', 'veknilash', 1), 
(235, 'Velen', 'velen', 1), 
(236, 'Warsong', 'warsong', 1), 
(237, 'Whisperwind', 'whisperwind', 1), 
(238, 'Wildhammer', 'wildhammer', 1), 
(239, 'Windrunner', 'windrunner', 1), 
(240, 'Winterhoof', 'winterhoof', 1), 
(241, 'Wyrmrest Accord', 'wyrmrest-accord', 1), 
(242, 'Ysera', 'ysera', 1), 
(243, 'Ysondre', 'ysondre', 1), 
(244, 'Zangarmarsh', 'zangarmarsh', 1), 
(245, 'Zul''jin', 'zuljin', 1), 
(246, 'Zuluhed', 'zuluhed', 1);